// MARK: - Generate Command

import ArgumentParser
import Foundation
import PermissionKit

struct GenerateCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "generate",
        abstract: "Generate Info.plist, entitlements, and xcconfig from your .permissionkit.yml"
    )

    @Option(name: .long, help: "Path to the YAML config file (default: .permissionkit.yml)")
    var config: String = ".permissionkit.yml"

    @Option(name: .long, help: "Your app's name for generated filenames")
    var appName: String?

    @Option(name: .long, help: "Directory to write generated files")
    var outputDir: String?

    mutating func run() throws {
        let configPath = resolvedPath(config)

        guard FileManager.default.fileExists(atPath: configPath) else {
            throw ValidationError("Config file not found: \(configPath)\nRun 'permissionkit init' to create one.")
        }

        let yamlConfig = try ConfigParser.load(from: configPath)

        // CLI flags override YAML values
        let resolvedAppName = appName ?? yamlConfig.appName ?? "App"
        let resolvedOutputDir = outputDir ?? yamlConfig.outputDir ?? "."

        let manifest = ConfigParser.manifest(from: yamlConfig)

        guard !manifest.entries.isEmpty else {
            throw ValidationError("No valid permissions found in \(configPath)")
        }

        // Print report
        print(manifest.report())
        print()

        // Ensure output directory exists
        let outputPath = resolvedPath(resolvedOutputDir)
        try FileManager.default.createDirectory(atPath: outputPath, withIntermediateDirectories: true)

        var generatedFiles: [String] = []

        // Generate Info.plist
        let plistEntries = manifest.generateInfoPlistEntries()
        if !plistEntries.isEmpty {
            let plistPath = (outputPath as NSString).appendingPathComponent("\(resolvedAppName)-Info.plist")
            let bundleId = yamlConfig.bundleIdentifier ?? "$(PRODUCT_BUNDLE_IDENTIFIER)"
            let fullPlist = manifest.generateInfoPlist(bundleIdentifier: bundleId)
            try fullPlist.write(toFile: plistPath, atomically: true, encoding: .utf8)
            generatedFiles.append(plistPath)
            print("✅ Generated Info.plist → \(plistPath)")
        }

        // Generate entitlements
        let entitlementsDict = manifest.generateEntitlements()
        if !entitlementsDict.isEmpty {
            let entPath = (outputPath as NSString).appendingPathComponent("\(resolvedAppName).entitlements")
            let entitlementsPlist = manifest.generateEntitlementsPlist()
            try entitlementsPlist.write(toFile: entPath, atomically: true, encoding: .utf8)
            generatedFiles.append(entPath)
            print("✅ Generated entitlements → \(entPath)")
        }

        // Generate xcconfig
        let xcconfigPath = (outputPath as NSString).appendingPathComponent("\(resolvedAppName).xcconfig")
        let xcconfig = generateXcconfig(from: manifest, appName: resolvedAppName)
        try xcconfig.write(toFile: xcconfigPath, atomically: true, encoding: .utf8)
        generatedFiles.append(xcconfigPath)
        print("✅ Generated xcconfig → \(xcconfigPath)")

        // Generate Bonjour services if applicable
        if let services = yamlConfig.bonjourServices, !services.isEmpty {
            if let bonjourXML = manifest.generateBonjourServices(serviceTypes: services) {
                print()
                print("📡 Bonjour Services (add to Info.plist):")
                print(bonjourXML)
            }
        }

        print()
        print("Done! Add these files to your \(resolvedAppName) Xcode project.")
    }

    private func generateXcconfig(from manifest: PermissionManifest, appName: String) -> String {
        var lines = [
            "// Auto-generated by PermissionKit CLI",
            "// Add this file to your \(appName) target's build settings",
            ""
        ]

        let entitlements = manifest.generateEntitlements()
        if !entitlements.isEmpty {
            lines.append("CODE_SIGN_ENTITLEMENTS = \(appName).entitlements")
        }

        let plistEntries = manifest.generateInfoPlistEntries()
        if !plistEntries.isEmpty {
            lines.append("INFOPLIST_FILE = \(appName)-Info.plist")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private func resolvedPath(_ path: String) -> String {
        if path.hasPrefix("/") { return path }
        return (FileManager.default.currentDirectoryPath as NSString).appendingPathComponent(path)
    }
}
