// MARK: - PermissionKit Plist Generator CLI

import Foundation
#if canImport(PermissionKit)
import PermissionKit
#endif

/// Command line tool that reads a `permissions.json` configuration file
/// and generates the required Info.plist entries and .entitlements file.
///
/// Usage:
///   permission-plist-generator <permissions.json> [--output-dir <dir>]
///   permission-plist-generator --help
@main
struct PermissionPlistGenerator {
    static func main() throws {
        let args = CommandLine.arguments

        if args.contains("--help") || args.contains("-h") {
            printUsage()
            return
        }

        // Find the JSON config file path
        guard args.count >= 2 else {
            printError("Missing required argument: path to permissions.json")
            printUsage()
            exit(1)
        }

        let configPath = args[1]

        // Parse output directory
        var outputDir = FileManager.default.currentDirectoryPath
        if let idx = args.firstIndex(of: "--output-dir"), idx + 1 < args.count {
            outputDir = args[idx + 1]
        }

        // Load and parse the manifest
        let manifest: PermissionManifest
        do {
            manifest = try PermissionManifest(jsonFileAt: configPath)
        } catch {
            printError("Failed to parse \(configPath): \(error.localizedDescription)")
            exit(1)
        }

        guard !manifest.entries.isEmpty else {
            printError("No permissions found in \(configPath)")
            exit(1)
        }

        // Print report
        print(manifest.report())
        print("")

        // Generate Info.plist entries
        let plistEntries = manifest.generateInfoPlistEntries()
        if !plistEntries.isEmpty {
            let plistPath = (outputDir as NSString).appendingPathComponent("PermissionKit-Info.plist")
            let fullPlist = manifest.generateInfoPlist()
            try fullPlist.write(toFile: plistPath, atomically: true, encoding: .utf8)
            print("✅ Generated Info.plist entries → \(plistPath)")
        }

        // Generate entitlements
        let entitlementsPlist = manifest.generateEntitlementsPlist()
        let entitlementsDict = manifest.generateEntitlements()
        if !entitlementsDict.isEmpty {
            let entPath = (outputDir as NSString).appendingPathComponent("PermissionKit.entitlements")
            try entitlementsPlist.write(toFile: entPath, atomically: true, encoding: .utf8)
            print("✅ Generated entitlements → \(entPath)")
        }

        // Generate xcconfig snippet
        let xcconfigPath = (outputDir as NSString).appendingPathComponent("PermissionKit.xcconfig")
        let xcconfig = generateXcconfig(from: manifest)
        try xcconfig.write(toFile: xcconfigPath, atomically: true, encoding: .utf8)
        print("✅ Generated xcconfig → \(xcconfigPath)")

        print("")
        print("Done! Add these files to your Xcode project.")
    }

    static func generateXcconfig(from manifest: PermissionManifest) -> String {
        var lines = [
            "// Auto-generated by PermissionKit Plist Generator",
            "// Add this file to your Xcode project build settings",
            ""
        ]

        // Point to generated entitlements
        let entitlements = manifest.generateEntitlements()
        if !entitlements.isEmpty {
            lines.append("CODE_SIGN_ENTITLEMENTS = PermissionKit.entitlements")
        }

        // Point to generated Info.plist
        let plistEntries = manifest.generateInfoPlistEntries()
        if !plistEntries.isEmpty {
            lines.append("INFOPLIST_FILE = PermissionKit-Info.plist")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    static func printUsage() {
        print("""
        USAGE: permission-plist-generator <permissions.json> [--output-dir <dir>]

        Reads a permissions.json configuration and generates:
          • Info.plist with required privacy usage descriptions
          • .entitlements file with required capabilities
          • .xcconfig file for build settings

        ARGUMENTS:
          <permissions.json>    Path to your permissions configuration file

        OPTIONS:
          --output-dir <dir>    Directory to write generated files (default: current dir)
          --help, -h            Show this help message

        JSON FORMAT:
        {
          "permissions": [
            { "permission": "camera", "usage": "Take photos for your profile" },
            { "permission": "location", "variant": "whenInUse", "usage": "Show nearby places" },
            { "permission": "photos", "variant": "readWrite", "usage": "Save edited images" },
            { "permission": "notifications", "usage": "Send you order updates" },
            { "permission": "health", "variant": "readWrite", "usage": "Track your workouts" },
            { "permission": "biometrics", "variant": "faceID", "usage": "Secure app login" }
          ]
        }

        SUPPORTED PERMISSIONS:
          camera, microphone, location, photos, contacts, calendar, reminders,
          notifications, criticalAlerts, bluetooth, localNetwork, nearbyInteraction,
          biometrics, tracking, siri, speechRecognition, health, motion, homeKit,
          nfc, mediaLibrary, screenRecording, fullDiskAccess, accessibility,
          inputMonitoring, automation, workoutExtension, mindfulnessSession

        VARIANTS:
          location:   whenInUse (default), always, precise
          photos:     readWrite (default), addOnly, limited
          calendar:   fullAccess (default), read, write
          health:     readWrite (default), read, write
          biometrics: any (default), faceID, touchID
        """)
    }

    static func printError(_ message: String) {
        let stderr = FileHandle.standardError
        stderr.write(Data("Error: \(message)\n".utf8))
    }
}

extension FileHandle: @retroactive TextOutputStream {
    public func write(_ string: String) {
        let data = Data(string.utf8)
        self.write(data)
    }
}
